alfresco:
  general:
    networkPolicies:
      enabled: false
  ingress:
    host: mydomain.xenit.eu
    protocol: https
    kubernetes.io/ingress.class: {}
    ingressAnnotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-production"
  imageCredentials:
    private:
      username: hello
      password: world
    alfresco:
      username: hello
      password: world
  acs:
    resources:
      requests:
        memory: "1Gi"
        cpu: "0"    
  mq:
    resources:
      requests:
        memory: "1Gi"
        cpu: "0"
  postgresql:
    resources:
      requests:
        memory: "1Gi"
        cpu: "0"
  solr:
    enabled: false
  transformServices:
    enabled: false
  digitalWorkspace:
    enabled: false
letsencrypt:
  email: test@test.eu